export const actionTypes = {
  //User Actions Types.........
  SET_LOGIN_TOKEN: "SET_LOGIN_TOKEN",
  SET_NEW_USER_ADD: "SET_NEW_USER_ADD",
  GET_USERS: "GET_USERS",
  EDIT_USERS: "EDIT_USERS",
  DELETE_USER: "DELETE_USER",

  //Products Actions Types.........

  PRODUCT_ADD: "PRODUCT_ADD",
  PRODUCT_EDIT: "PRODUCT_EDIT",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_LIST: "PRODUCT_LIST",
};
